//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCT.HotkeyKanban.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class HotkeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotkeySettings defaultInstance = ((HotkeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotkeySettings())));
        
        public static HotkeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::KCT.HotkeyKanban.HotkeyAPI.Keys Key {
            get {
                return ((global::KCT.HotkeyKanban.HotkeyAPI.Keys)(this["Key"]));
            }
            set {
                this["Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public global::KCT.HotkeyKanban.HotkeyAPI.ModifierKeys ModifierKey {
            get {
                return ((global::KCT.HotkeyKanban.HotkeyAPI.ModifierKeys)(this["ModifierKey"]));
            }
            set {
                this["ModifierKey"] = value;
            }
        }
    }
}
